name: CI

on: 
  pull_request:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:

      - name: Echo Infomation
        run: |
          echo "event name: ${{github.event_name}}"
          echo "event action: ${{github.event.action}}"
          echo "event number: ${{github.event.number}}"

      - uses: actions/checkout@v1

      - name: Cache
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci
        env:
          CI: true

      - name: Build
        run: |
          npm run build
        env:
          CI: true

      - name: Test
        run: |
          npm run test
        env:
          CI: true

      - name: Create Changelogs
        id: changelog
        uses: heineiuo/create-changelogs@master

      - name: Publish to NPM (Pre-release)
        if: |
          github.event_name == 'push' && steps.changelog.outputs.valid == 'true' && steps.changelog.outputs.is_prerelease == 'true'
        run: |
          echo '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}' > ~/.npmrc
          npm publish --access=public --tag=next

      - name: Publish to NPM (Release)
        if: |
          github.event_name == 'push' && steps.changelog.outputs.valid == 'true' && steps.changelog.outputs.is_prerelease == 'false'
        run: |
          echo '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}' > ~/.npmrc
          npm publish --access=public

      - name: Create Github Release
        if: |
          github.event_name == 'push' && steps.changelog.outputs.valid == 'true'
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.changelog.outputs.raw }}
          draft: false
          body: ${{ steps.changelog.outputs.changelogs }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease:
            ${{ steps.changelog.outputs.is_prerelease == 'true' }}